#!/usr/bin/env bash
# Proves init and sync write what they should into a project, and leave alone
# what is not theirs.
#
#   bash test/run-sync.sh
#
# Focus: the files shared with the project. The agents' settings files hold
# the project's own permissions and hooks as well as the harness entry, so
# sync must add, update and remove exactly its own entry and nothing else.

set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$(cd "$HERE/../bin" && pwd)/harness.js"
PASS=0; FAILN=0
TMPROOT="$(mktemp -d)"
trap 'rm -rf "$TMPROOT"' EXIT

ok()   { PASS=$((PASS + 1)); printf '  ok    %s\n' "$1"; }
fail() { FAILN=$((FAILN + 1)); printf '  FAIL  %s\n' "$1"; [ -n "${2:-}" ] && printf '%s\n' "$2" | sed 's/^/        /'; }
check() { local name="$1"; shift; if "$@" >/dev/null 2>&1; then ok "$name"; else fail "$name"; fi; }
# js <expression over `j`, the parsed JSON file>: true/false
json() { node -e "const j=JSON.parse(require('fs').readFileSync('$1','utf8')); process.exit(($2) ? 0 : 1)"; }

REPO="$TMPROOT/app"; mkdir -p "$REPO"; cd "$REPO"
git init -q -b play
printf '{ "name": "app", "private": true, "dependencies": { "next": "15.0.0" } }\n' > package.json
mkdir -p .claude .cursor
cat > .claude/settings.json <<'JSON'
{
  "permissions": { "allow": ["Bash(npm run test:unit)"] },
  "hooks": {
    "Stop": [ { "hooks": [ { "type": "command", "command": "say done" } ] } ]
  }
}
JSON
cat > .cursor/hooks.json <<'JSON'
{ "version": 1, "hooks": { "stop": [ { "command": ".cursor/hooks/notify.sh" } ], "afterFileEdit": [ { "command": "npx prettier --write" } ] } }
JSON

node "$BIN" init >/dev/null 2>&1

echo "claude code output"
check "rules are written as .claude/rules/*.md" test -f .claude/rules/10-boundaries.md
check "a scoped rule carries paths frontmatter" grep -q '^paths:' .claude/rules/16-nextjs.md
check "an always-on rule has no frontmatter" bash -c '! head -1 .claude/rules/00-working-agreement.md | grep -q "^---"'
check "no Supabase rule without Supabase" test ! -f .claude/rules/15-supabase.md
check "commands are written to .claude/commands" test -f .claude/commands/threat.md
check "rituals never run on the model's own initiative" grep -q '^disable-model-invocation: true' .claude/commands/threat.md
check "commands carry a description" grep -q '^description: "Adversarial security pass' .claude/commands/threat.md
check "the header sits right after the frontmatter" bash -c "sed -n 6p .claude/commands/threat.md | grep -q 'Generated by kei-interactive-harness'"
check "no CLAUDE.md is written (Claude Code reads AGENTS.md)" test ! -f CLAUDE.md
check "the reviewer subagent is written where both agents read it" test -f .claude/agents/harness-reviewer.md
check "its frontmatter comes first" bash -c "head -2 .claude/agents/harness-reviewer.md | grep -q '^name: harness-reviewer'"
check "it is read-only in Cursor" grep -q '^readonly: true' .claude/agents/harness-reviewer.md

echo "end-of-turn hook entries"
check "claude: the project's permissions survive" json .claude/settings.json 'j.permissions.allow[0]==="Bash(npm run test:unit)"'
check "claude: the project's own Stop hook survives" json .claude/settings.json 'j.hooks.Stop.some(g=>g.hooks.some(h=>h.command==="say done"))'
check "claude: the harness entry is added" json .claude/settings.json 'j.hooks.Stop.some(g=>g.hooks.some(h=>/harness turn --agent claude/.test(h.command)))'
check "cursor: the project's hooks survive" json .cursor/hooks.json 'j.hooks.stop.some(h=>h.command===".cursor/hooks/notify.sh") && j.hooks.afterFileEdit.length===1'
check "cursor: the harness entry is added, one follow-up max" json .cursor/hooks.json 'j.hooks.stop.some(h=>/harness turn --agent cursor/.test(h.command) && h.loop_limit===1)'

node "$BIN" sync >/dev/null 2>&1
node "$BIN" sync >/dev/null 2>&1
check "claude: repeated syncs never duplicate the entry" json .claude/settings.json 'j.hooks.Stop.flatMap(g=>g.hooks).filter(h=>/harness turn/.test(h.command)).length===1'
check "cursor: repeated syncs never duplicate the entry" json .cursor/hooks.json 'j.hooks.stop.filter(h=>/harness turn/.test(h.command)).length===1'
check "the local settings file is gitignored" grep -qx '.claude/settings.local.json' .gitignore

echo "narrowing to one agent"
mkdir -p .harness; printf 'HARNESS_AGENTS="cursor"\n' >> .harness/config.sh
printf '# my own rule\n' > .claude/rules/90-mine.md
node "$BIN" sync >/dev/null 2>&1
check "harness-written claude rules are removed" test ! -f .claude/rules/10-boundaries.md
check "harness-written claude commands are removed" test ! -f .claude/commands/threat.md
check "the project's own claude rule stays" test -f .claude/rules/90-mine.md
check "claude: the harness entry is removed" json .claude/settings.json '!JSON.stringify(j).includes("harness turn")'
check "claude: the project's own hook and permissions stay" json .claude/settings.json 'j.permissions && j.hooks.Stop[0].hooks[0].command==="say done"'
check "cursor output is untouched" test -f .cursor/rules/10-boundaries.mdc
check "the reviewer stays for Cursor, which reads .claude/agents" test -f .claude/agents/harness-reviewer.md

echo "switching the turn check off"
printf 'HARNESS_DISABLE="turn"\n' >> .harness/config.sh
node "$BIN" sync >/dev/null 2>&1
check "cursor: the harness entry is removed" json .cursor/hooks.json '!JSON.stringify(j).includes("harness turn")'
check "cursor: the project's hooks stay" json .cursor/hooks.json 'j.hooks.stop[0].command===".cursor/hooks/notify.sh"'

echo "a settings file that is not valid JSON"
printf 'HARNESS_AGENTS="cursor claude"\n' > .harness/config.sh
printf '{ not json' > .claude/settings.json
OUT="$(node "$BIN" sync 2>&1)"
check "sync says it skipped it" bash -c "printf '%s' \"\$0\" | grep -q 'not valid JSON'" "$OUT"
check "and does not rewrite it" grep -qx '{ not json' .claude/settings.json

echo "doctor"
printf '{}\n' > .claude/settings.json
node "$BIN" sync >/dev/null 2>&1
printf '# Project notes\n' > CLAUDE.md
OUT="$(node "$BIN" doctor 2>&1)"
check "doctor flags a CLAUDE.md that hides AGENTS.md" bash -c "printf '%s' \"\$0\" | grep -q 'without importing AGENTS.md'" "$OUT"
printf '# Project notes\n@AGENTS.md\n' > CLAUDE.md
OUT="$(node "$BIN" doctor 2>&1)"
check "and is quiet once it imports it" bash -c "! printf '%s' \"\$0\" | grep -q 'without importing AGENTS.md'" "$OUT"
check "doctor reports both hooks" bash -c "[ \$(printf '%s' \"\$0\" | grep -c 'hooked') -eq 2 ]" "$OUT"

echo
if [ "$FAILN" -eq 0 ]; then echo "all $PASS passed"; exit 0; fi
echo "$FAILN failed, $PASS passed"; exit 1
